Week_2/Week_2_Assignment/copilot-main/VehicleInsuranceClient/Controllers/CertificateController.cs
using DataAccess.Models;
using Microsoft.AspNetCore.Mvc;
using System.Reflection;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using VehicleInsuranceClient.Helper;
using VehicleInsuranceClient.Models;
using VehicleInsuranceClient.Models.Dtos;

namespace VehicleInsuranceClient.Controllers
{
    public class CertificateController : Controller
    {
        public static List<CertificateModel> Certificates = new List<CertificateModel>();
        private readonly IWebHostEnvironment _env;
        HttpClient httpClient = new HttpClient();

        public CertificateController(IWebHostEnvironment env)
        {
            _env = env;
        }

        public IActionResult Index()
        {
            var userString = HttpContext.Session.GetString("user");
            if (userString == null)
            {
                string returnUrl = HttpContext.Request.Path;
                return RedirectToAction("Login", "Account", new { returnUrl = returnUrl });
            }

            var obj = Newtonsoft.Json.JsonConvert.DeserializeObject<Customer>(userString);
            var userResult = Newtonsoft.Json.JsonConvert.DeserializeObject<CustomerDto>
                (httpClient.GetStringAsync(@Program.ApiAddress + "/Customer/" + obj.Id).Result);
            ViewBag.userID = userResult.Id;
            ViewBag.userName = userResult.CustomerName;

            return View();
        }

        /// <summary>
        /// Create view for ListCertificates
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult GetCertificates([FromBody] List<CertificateModel> model)
        {
            Certificates = model;
            return View("ListCertificates", model);
        }

        public IActionResult Details(int id)
        {
            if (Certificates == null)
            {
                Certificates = InitializeCertificates();
            }

            // Check Login
            var userString = HttpContext.Session.GetString("user");
            if (userString == null)
            {
                string returnUrl = HttpContext.Request.Path;
                return RedirectToAction("Login", "Account", new { returnUrl = returnUrl });
            }

            CertificateModel model = Certificates.Where(c => c.Id == id).FirstOrDefault();

            if (model == null)
            {
                return RedirectToAction("Index");
            }

            return View(model);
        }

        private List<CertificateModel> InitializeCertificates()
        {
            var response = httpClient.GetAsync(Program.ApiAddress + "/Certificate/GetCertificates").Result;
            var data = response.Content.ReadAsStringAsync().Result;
            if (data != null)
            {
                List<CertificateModel> certificate = JsonSerializer.Deserialize<List<CertificateModel>>(data);
                return certificate;
            }

            return null;
        }

        public IActionResult Print(int id)
        {
            CertificateModel model = Certificates.Where(c => c.Id == id).FirstOrDefault();

            return View(model);
        }

        /// <summary>
        /// Create View for customer fill-in the Contract
        /// </summary>
        /// <returns>Contract View</returns>
        [HttpGet]
        [Route("Certificate/Contract/{estimateNo?}")]
        public IActionResult Contract(string estimateNo)
        {
            if (String.IsNullOrEmpty(estimateNo))
            {
                TempData["EstimateNoErrMessage"] = "Please get your estimate!";
                return RedirectToAction("Index", "Estimate");
            }
            var contractCookie = Request.Cookies[estimateNo];
            if (contractCookie == null)
            {
                TempData["EstimateNoErrMessage"] = "Your estimate number is invalid! Please get another!";
                return RedirectToAction("Index", "Estimate");
            }
            ContractModel contract;
            try
            {
                // Check Login
                var userString = HttpContext.Session.GetString("user");
                if (userString == null)
                {
                    string returnUrl = HttpContext.Request.Path + $"/{estimateNo}";
                    return RedirectToAction("Login", "Account", new { returnUrl = returnUrl });
                }
                CustomerDto customer = JsonSerializer.Deserialize<CustomerDto>(userString);

                if (customer == null)
                {
                    return RedirectToAction("Login", "Account");
                }
                contract = JsonSerializer.Deserialize<ContractModel>(contractCookie.Normalize())!;

                contract.Contract.CustomerName = customer.CustomerName;
                contract.Contract.CustomerPhone = customer.CustomerPhone;
                contract.Contract.CustomerAddress = customer.CustomerAddress;

                ViewBag.PolicyType = EstimateController.Instance.GetPolicies().Where(p => p.PolicyId == contract.Estimation.PolicyId).Select(m => m.PolicyType).FirstOrDefault();
            }
            catch (Exception)
            {
                TempData["EstimateNoErrMessage"] = "Your estimate number is invalid! Sorry for the inconvenience! Please get another!";
                return RedirectToAction("Index", "Estimate");
            }

            return View(contract);
        }

        /// <summary>
        /// Create Certificate after customer submit Contract form
        /// </summary>
        /// <param name="model">Contract</param>
        /// <returns>Certificates of a customer</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Contract(ContractModel model)
        {
            var userString = HttpContext.Session.GetString("user");
            if (userString == null)
            {
                string returnUrl = HttpContext.Request.Path;
                return RedirectToAction("Login", "Account", new { returnUrl = returnUrl });
            }
            // CHECKLOGIN
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            string estimateNo = model.Estimation.EstimateNo.ToString();
            if (String.IsNullOrEmpty(estimateNo))
            {
                TempData["EstimateNoErrMessage"] = "Please get your estimate!";
                return RedirectToAction("Index", "Estimate");
            }
            var contractCookie = Request.Cookies[estimateNo];
            if (contractCookie == null)
            {
                TempData["EstimateNoErrMessage"] = "Your estimate number is invalid! Please get another!";
                return RedirectToAction("Index", "Estimate");
            }

            // Save the input information of the contract into the same cookie. BUT without IFormFile type
            // Purpose: In case errors occur while creating Certificate, customer will not loss the contract form information they did input.
            IFormFileCollection proveFiles = model.Contract.Prove;
            if (proveFiles == null)
            {
                return View(model);
            }
            model.Contract.Prove = null;
            CookieHelper.CreateCookie(HttpContext, estimateNo.ToString(), model);

            try
            {
                #region Upload prove images
                string pathImages = SaveImages(proveFiles);
                if (String.IsNullOrWhiteSpace(pathImages))
                {
                    return View(model);
                }
                #endregion Upload prove images

                #region Post create Certificate to database
                int policyNo = StoreCertificate(model, pathImages);
                if (policyNo <= 0)
                {
                    TempData["EstimateNoErrMessage"] = "Something wrong with your estimate! Please get another!";
                    return View();
                }
                #endregion Post create Certificate to database
            }
            catch (Exception)
            {
                TempData["EstimateNoErrMessage"] = "Something wrong with your estimate! Please get another!";
                return RedirectToAction("Index", "Estimate");
            }
            // In case create certificate and upload prove images successfully. Remove the cookie.
            CookieHelper.RemoveCookie(HttpContext, estimateNo.ToString());
            return RedirectToAction("Index");
        }
        private string SaveImages(IFormFileCollection files)
        {
            string resultImagesPath = String.Empty;
            if (files == null) return resultImagesPath;
            Regex regex = new Regex(@"[~^$*+`?()>;[\]{}\|/&!@#%]");
            foreach (IFormFile file in files)
            {
                if (file.Length == 0 || file == null)
                {
                    return resultImagesPath;
                }
                if (regex.IsMatch(file.FileName))
                {
                    ViewBag.InvalidNameImage = "Image name cannot contain special letters";
                    return resultImagesPath;
                }
                string checkExtention = Path.GetExtension(file.FileName);
                if (!(checkExtention.Equals(".png") || checkExtention.Equals(".jpg") || checkExtention.Equals(".jpeg")))
                {
                    ViewBag.InvalidNameImage = "Only accept image types of jpg, png and jpeg";
                    return resultImagesPath;
                }
            }
            // Check if directory for prove images didn't exist in Web App. Create new one
            string datePath = DateTime.Now.ToString("yyyMMdd");
            string directory = Path.Combine("img", "proveGallery", datePath);
            string filePath = Path.Combine(_env.WebRootPath, directory);
            if (!Directory.Exists(filePath))

Week_2/Week_2_Assignment/copilot-main/VehicleInsuranceClient/Controllers/PolicyController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using VehicleInsuranceClient.Models;

namespace VehicleInsuranceClient.Controllers
{
    public class PolicyController : Controller
    {
        public static List<PolicyModel> Policies = new List<PolicyModel>();
        public HttpClient client = new HttpClient();

        public IActionResult Index()
        {
            var userString = HttpContext.Session.GetString("user");
            if (userString == null)
            {
                return RedirectToAction("Login", "Account");
            }
            return View();
        }

        /// <summary>
        /// Create view for ListPolicies
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult GetPolicies([FromBody] List<PolicyModel> model)
        {
            Policies = model;
            return View("ListPolicies", model);
        }

        public IActionResult CompleteCareCI()
        {   //Get Policy Data through API Controller and display it to View
            var model = JsonConvert.DeserializeObject<IEnumerable<PolicyModel>>(client.GetStringAsync(Program.ApiAddress + "/Policy/GetPolicies").Result);
            return View(model);
        }

        public IActionResult ComprehensiveCI()
        {   //Get Policy Data through API Controller and display it to View
            var model = JsonConvert.DeserializeObject<IEnumerable<PolicyModel>>(client.GetStringAsync(Program.ApiAddress + "/Policy/GetPolicies").Result);
            return View(model);
        }

        public IActionResult ThirdPartyFireAndTheftCI()
        {   //Get Policy Data through API Controller and display it to View
            var model = JsonConvert.DeserializeObject<IEnumerable<PolicyModel>>(client.GetStringAsync(Program.ApiAddress + "/Policy/GetPolicies").Result);
            return View(model);
        }

        public IActionResult ThirdPartyPropertyDamageCI()
        {
            //Get Policy Data through API Controller and display it to View
            var model = JsonConvert.DeserializeObject<IEnumerable<PolicyModel>>(client.GetStringAsync(Program.ApiAddress + "/Policy/GetPolicies").Result);
            return View(model);
        }
    }
}

Week_2/Week_2_Assignment/copilot-main/VehicleInsuranceClient/Views/Shared/_Footer.cshtml
<footer>
    <div class="container">
        <div class="row">

            <div class="col-md-6">
                <h3><img src="~/img/logo/logo.png" asp-append-version="true" style="width:100px;" /></h3>
                <p class="text-muted large">We are here to help you</p>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telephone-fill" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z" />
                </svg>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope-fill" viewBox="0 0 16 16">
                    <path d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555zM0 4.697v7.104l5.803-3.558L0 4.697zM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757zm3.436-.586L16 11.801V4.697l-5.803 3.546z" />
                </svg>
            </div>

            <div class="col-md-3">
                <h5 class="text-muted">Features</h5>
                <ul class="list-unstyled">
                    <li>
                        <a asp-controller="Home" asp-action="AboutUs">About Us</a>
                    </li>
                    <li>
                        <a href="#">Sitemap</a>
                    </li>
                    <li>
                        <a asp-controller="Home" asp-action="Contact">Contact</a>
                    </li>
                </ul>
            </div>

            <div class="col-md-3">
                <h5 class="text-muted">Follow Us</h5>
                @*<ul class="list-unstyled">
                    <li>
                        <a href="#">Terms of Service</a>
                    </li>
                    <li>
                        <a href="#">Privacy Policy</a>
                    </li>
                    <li>
                        <a href="#">Customer Policy</a>
                    </li>
                    <li>
                        <a href="#">Documentation</a>
                    </li>
                </ul>*@
                <div class="d-flex">
                    <a class="btn btn-outline-primary btn-square me-2" href="#"><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-outline-primary btn-square me-2" href="#"><i class="fab fa-facebook"></i></a>
                    <a class="btn btn-outline-primary btn-square me-2" href="#"><i class="fab fa-linkedin"></i></a>
                    <a class="btn btn-outline-primary btn-square" href="#"><i class="fab fa-instagram"></i></a>
                </div>
            </div>

        </div>  <!-- End of Row -->
    </div>  <!-- End of Container -->
</footer> <!-- End of Footer -->

Week_2/Week_2_Assignment/copilot-main/VehicleInsuranceClient/Views/Shared/_Header.cshtml
@using Microsoft.AspNetCore.Http;

<div class="container-fluid bg-white">
    <div class="container">
        <div class="header-top-bar">
            <nav class="top-nav-bar">
                <ul class="top-grid pt-3">
                    <li class="nav-bar-item">
                        <a class="text-link" asp-controller="Home" asp-action="AboutUs">
                            About Us
                        </a>
                    </li>
                    <li class="nav-bar-item">
                        <a class="text-link" asp-controller="Home" asp-action="Sitemap">
                            Sitemap
                        </a>
                    </li>
                    <li class="nav-bar-item">
                        <a class="text-link" asp-controller="Home" asp-action="Contact">
                            Contact
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
    <!-- Navigation Bar -->
    <div class="container">
        <nav class="navbar navbar-expand-lg pb-3">

            <a asp-action="Index" asp-controller="Home" class="navbar-brand"><img src="~/img/logo/logo.png" asp-append-version="true" style="width:150px;" /></a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#res_nav">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Collapsing Menu and Links -->
            <div class="collapse navbar-collapse" id="res_nav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <div class="dropdown">
                            <a id="coverageBtn" class="nav-link text-dark dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Coverage Plans</a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item text-dark" asp-controller="Policy" asp-action="ThirdPartyFireAndTheftCI">Third-Party Fire and Theft</a></li>
                                <li><a class="dropdown-item text-dark" asp-controller="Policy" asp-action="ThirdPartyPropertyDamageCI">Third-Party Property Damage</a></li>
                                <li><a class="dropdown-item text-dark" asp-controller="Policy" asp-action="ComprehensiveCI">Comprehensive</a></li>
                                <li><a class="dropdown-item text-dark" asp-controller="Policy" asp-action="CompleteCareCI">Complete Care®</a></li>
                            </ul>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Home" asp-action="Testimonials">Testimonials</a>
                    </li>
                </ul>

                @{
                    if (Context.Session.GetString("user") != null)
                    {
                        <ul class="navbar-nav ms-5">
                            <li>
                                <a asp-controller="Certificate" asp-action="Index" class="btn btn-primary me-5" style="background:white !important; color: #0e6fc5 !important;">My Certificates</a>
                            </li>
                            <li>
                                <a asp-controller="Account" asp-action="Logout" class="btn btn-primary">Logout</a>
                            </li>    
                        </ul>
                    }

                    else
                    {
                        <ul class="navbar-nav ms-5">
                            <li>
                                <a asp-controller="Account" asp-action="Login" class="btn btn-primary">Log In</a>
                            </li>
                        </ul>
                    }
                }

            </div>  <!-- End of Collapsing Menu and Links -->
        </nav>  <!-- End of Navigation Bar -->
    </div>
    <!-- End of Header -->
</div>

Week_2/Week_2_Assignment/copilot-main/VehicleInsuranceClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/customer.css" asp-append-version="true" />
</head>

<body>
        <partial name="_Header" />
        @RenderBody()
        <partial name="_Footer" />
</body>
</html>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

@await RenderSectionAsync("validateScripts", required: false)

@await RenderSectionAsync("Scripts", required: false)

Week_2/Week_2_Assignment/copilot-main/VehicleInsuranceClient/Views/Shared/_LayoutEmployee.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VehicleInsuranceClient</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/20.1.55/material.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/employee.css" asp-append-version="true" />
    <link rel="stylesheet" type="text/css" href="~/lib/DataTables/css/datatables.min.css" asp-append-version="true" />
    <script src="https://cdn.syncfusion.com/ej2/20.1.55/dist/ej2.min.js"></script>
</head>

<body>

    <partial name="_Sidebar" />

    <section id="header">
        <div class="navigation">
            <!-- Search -->
            <div class="hamburger">
                <div>
                    <i id="header-btn" class="fas fa-bars"></i>
                </div>
                <div class="search">
                    <i class="fas fa-search"></i>
                    <form action="">
                        <input type="text" placeholder="Search...">
                    </form>
                </div>
            </div>
            <!-- Profile -->
          @*  <div class="profile">
                <img src="" alt="profile-image">
            </div>*@
        </div>

        @RenderBody()

    </section>

    <ejs-scripts></ejs-scripts>
</body>
</html>


<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script type="text/javascript" src="~/lib/DataTables/js/datatables.min.js" asp-append-version="true"></script>
<script src="~/js/employee.js" asp-append-version="true"></script>

@await RenderSectionAsync("validateScripts", required: false)
@await RenderSectionAsync("Scripts", required: false)

Week_2/Week_2_Assignment/copilot-main/VehicleInsuranceClient/Views/Shared/_LineFooter.cshtml
<div id="line-footer">
    <div class="container-fluid">
        <div class="d-flex flex-row mb-3 justify-content-around">
            <div class="pt-4 d-flex flex-row">
                <div class="fw-bold fs-4 pe-2">
                    General enquiries
                </div>
                <div class="pt-1 d-flex flex-row">
                    <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="23px" height="23px" viewBox="0 0 500 500" style="enable-background:new 0 0 500 500;" xml:space="preserve">
                    <g>
                    <path d="M137.6,159c32.4-32.4,60.7-52.4,3.2-123.9S45,18.5,13.6,49.9c-36.3,36.3-2,171.4,131.6,305
		                    c133.5,133.5,268.7,167.8,304.9,131.6c31.4-31.4,86.3-69.7,14.8-127.2s-91.5-29.2-123.9,3.2c-22.6,22.7-79.9-24.6-129.4-74.1
		                    S114.8,181.6,137.6,159z"></path>
                    </g>
                    </svg>

                    <div class="fs-5">13 72 22</div>
                
                </div>
            </div>

            <div class="pt-4 d-flex flex-row justify-content-center">
                <div class="fw-bold fs-4 pe-2">
                    Roadside Assistance
                </div>
                <div class="pt-1 d-flex flex-row">
                    <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="23px" height="23px" viewBox="0 0 500 500" style="enable-background:new 0 0 500 500;" xml:space="preserve">
                    <g>
                    <path d="M137.6,159c32.4-32.4,60.7-52.4,3.2-123.9S45,18.5,13.6,49.9c-36.3,36.3-2,171.4,131.6,305
		                    c133.5,133.5,268.7,167.8,304.9,131.6c31.4-31.4,86.3-69.7,14.8-127.2s-91.5-29.2-123.9,3.2c-22.6,22.7-79.9-24.6-129.4-74.1
		                    S114.8,181.6,137.6,159z"></path>
                    </g>
                    </svg>

                    <div class="fs-5">13 55 55</div>

                </div>
            </div>
            <div class="pt-4 d-flex flex-row justify-content-center">
                <div class="fw-bold fs-4 pe-2">
                    Insurance Claims
                </div>
                <div class="pt-1 d-flex flex-row">
                    <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="23px" height="23px" viewBox="0 0 500 500" style="enable-background:new 0 0 500 500;" xml:space="preserve">
                    <g>
                    <path d="M137.6,159c32.4-32.4,60.7-52.4,3.2-123.9S45,18.5,13.6,49.9c-36.3,36.3-2,171.4,131.6,305
		                    c133.5,133.5,268.7,167.8,304.9,131.6c31.4-31.4,86.3-69.7,14.8-127.2s-91.5-29.2-123.9,3.2c-22.6,22.7-79.9-24.6-129.4-74.1
		                    S114.8,181.6,137.6,159z"></path>
                    </g>
                    </svg>

                    <div class="fs-5">13 19 99</div>

                </div>
            </div>
        </div>
    </div>  <!-- End of Container -->
</div>  <!-- End of line-footer -->