Week_2/Week_2_Assignment/copilot-main/VehicleInsuranceClient/Areas/Employee/Controllers/CompanyExpenseController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using VehicleInsuranceClient.Areas.Employee.Models;

namespace VehicleInsuranceClient.Areas.Employee.Controllers
{
    [Area("Employee")]
    public class CompanyExpenseController : Controller
    {
        public HttpClient client = new HttpClient();
        [HttpGet]
        public IActionResult Index()
        {
            var model = JsonConvert.DeserializeObject<IEnumerable<CompanyExpenseAdminModel>>(client.GetStringAsync(Program.ApiAddress + "/CompanyExpense/GetAllCompanyExpense").Result);
            return View(model);
        }

        [HttpGet]
        public IActionResult CompanyExpenseDetail(int claimNo)
        {
            var model = JsonConvert.DeserializeObject<IEnumerable<ClaimDetailCompanyExpenseAdminModel>>(client.GetStringAsync(Program.ApiAddress + "/CompanyExpense/GetCompanyExpenseDetail/" + claimNo).Result);
            return View(model);
        }
    }
}

Week_2/Week_2_Assignment/copilot-main/VehicleInsuranceClient/Areas/Employee/Views/CompanyExpense/CompanyExpenseDetail.cshtml
@using VehicleInsuranceClient.Areas.Employee.Models;
@model List<ClaimDetailCompanyExpenseAdminModel>
<!-- Title -->
<h3 class="title" style="text-align:center;">Claim Detail</h3>

<div class="container border w-50">
    <div class="p-4">
        <div>
            @foreach (ClaimDetailCompanyExpenseAdminModel item in Model.Where(u => u.Status == "Approved"))
            {
                <div class="d-flex flex-row">
                    <div class="fw-semibold me-3">Customer Name:</div> @item.CustomerName
                </div>
                <div class="d-flex flex-row">
                    <div class="fw-semibold me-3">Customer Address: </div> @item.CustomerAddress
                </div>
                <div class="d-flex flex-row">
                    <div class="fw-semibold me-3">Customer Phone: </div> @item.CustomerPhone
                </div>
                <hr />
                <div class="d-flex flex-row">
                    <div class="fw-semibold me-3">Policy no: </div> @item.PolicyNo
                </div>
                <div class="d-flex flex-row">
                    <div class="fw-semibold me-3">Policy Type: </div> @item.PolicyType
                </div>
                <div class="d-flex flex-row">
                    <div class="fw-semibold me-3">Policy Duration: </div> @item.PolicyDuration
                </div>
                <div class="d-flex flex-row">
                    <div class="fw-semibold me-3">Policy Date: </div> @item.PolicyDate.Value.ToString("ddMMMyyyy")
                </div>
                <div class="d-flex flex-row">
                    <div class="fw-semibold me-3">Policy Expired Day: </div> @item.ExpiryDate.Value.ToString("ddMMMyyyy")
                </div>
                <hr />
                <div class="d-flex flex-row">
                    <div class="fw-semibold me-3">Vehicle Name: </div> @item.VehicleName
                </div>
                <div class="d-flex flex-row">
                    <div class="fw-semibold me-3">Vehicle Version: </div> @item.VehicleVersion
                </div>
                <div class="d-flex flex-row">
                    <div class="fw-semibold me-3">Vehicle Model: </div> @item.VehicleModel
                </div>
                <div class="d-flex flex-row">
                    <div class="fw-semibold me-3">Vehicle Number: </div> @item.VehicleNumber
                </div>
                <div class="d-flex flex-row">
                    <div class="fw-semibold me-3">Vehicle Body Number: </div> @item.VehicleBodyNumber
                </div>
                <div class="d-flex flex-row">
                    <div class="fw-semibold me-3">Vehicle Engine Number: </div> @item.VehicleEngineNumber
                </div>
                <hr />
                <div class="d-flex flex-row">
                    <div class="fw-semibold me-3">Date Of Accident: </div> @item.DateOfAccident.ToString("ddMMMyyyy")
                </div>
                <div>
                    <div class="fw-semibold me-3">Image :</div>
                    <img src="~/img/Claim/@item.Image" style="height: 80px; width: 80px">
                </div>
                <div class="d-flex flex-row">
                    <div class="fw-semibold me-3">Insured Amount: </div> @item.InsuredAmount
                </div>
                <div class="d-flex flex-row">
                    <div class="fw-semibold me-3">Claimable Amount: </div> @item.ClaimableAmount
                </div>
                <div class="pb-3 d-flex flex-row">
                    <div class="d-flex align-items-center me-3 fw-semibold">Claim Status: </div>
                    @if (@item.Status == "Lodged")
                    {
                        <button type="button" class="btn btn-warning">@item.Status</button>
                    }
                    else if (@item.Status == "Inspecting")
                    {
                        <button type="button" class="btn btn-info">@item.Status</button>
                    }
                    else if (@item.Status == "Insufficient")
                    {
                        <button type="button" class="btn btn-secondary">@item.Status</button>
                    }
                    else if (@item.Status == "Approved")
                    {
                        <button type="button" class="btn btn-success">@item.Status</button>
                    }
                    else if (@item.Status == "Rejected")
                    {
                        <button type="button" class="btn btn-danger">@item.Status</button>
                    }
                    else
                    {
                        <div>@item.Status</div>
                    }
                </div>
            }
        </div>
    </div>
</div>
<div class="container my-4 p-4">
    <div style="text-align:right">
        <a asp-action="Index">Back To Company Expense List Page</a>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");

    }

}

Week_2/Week_2_Assignment/copilot-main/VehicleInsuranceClient/Areas/Employee/Views/CompanyExpense/Index.cshtml
@using VehicleInsuranceClient.Areas.Employee.Models;
@model List<CompanyExpenseAdminModel>
<!-- Title -->
<h3 class="title">Company Expense</h3>

<div class="container border my-4 p-4">
    <table id="myTable" class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Date Of Expense</th>
                <th>Type Of Expense</th>
                <th>Ammount Of Expense</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (CompanyExpenseAdminModel item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateOfExpense)
                    </td>
                    <td>
                        @item.TypeOfExpense
                    </td>
                    <td>
                        @item.AmountOfExpense
                    </td>
                    <td>
                    @*    <button type="btn m-2 btn-sm btn-warning" class="btn btn-info">@Html.ActionLink("Detail", "CompanyExpenseDetail", new {  CEId=item.Id })</button>*@
                        <a type="button" class="btn m-2 btn-sm btn-info" href="@Url.Action("CompanyExpenseDetail", "CompanyExpense", new { claimNo=item.ClaimNo })">Detail</a>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <th>Date Of Expense</th>
                <th>Type Of Expense</th>
                <th>Ammount Of Expense</th>
                <th>Action</th>
            </tr>
        </tfoot>
    </table>
</div>

<script>
    $(function () {
        $('#myTable').DataTable({
            "paging": true,
            "lengthChange": true,
            "searching": true,
            "ordering": true,
            "order": [
                [0, 'desc']
            ],
            "info": true,
            "autoWidth": false,
        });
    }());
</script>